---
## Checks
# check if first_master is already initialized
- name: Check if cluster is initialized
  stat:
    path: /etc/kubernetes/pki/ca.key
  register: isInitialized

## Initialize Cluster
- name: Copy file
  copy:
    src: ../output/kubeadm.yaml
    dest: /tmp/kubeadm.yaml
  when: not isInitialized.stat.exists

- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --config /tmp/kubeadm.yaml
  register: debugKubeadmInit
  when: not isInitialized.stat.exists

- name: Get worker join command
  command: kubeadm token create --print-join-command
  register: workerJoinCmd
  changed_when: False

- name: Get certification key
  shell: "kubeadm init phase upload-certs --upload-certs | tail -n 1"
  register: kubeCertKey
  changed_when: False

- name: Get master join command
  command: kubeadm token create --print-join-command --certificate-key {{ kubeCertKey.stdout }}
  register: masterJoinCmd
  changed_when: False

- name: "Add master join command to dummy host"
  add_host:
    name: "masterJoin"
    command: "{{ masterJoinCmd.stdout }}"
  changed_when: False

- name: "Add worker join command to dummy host"
  add_host:
    name: "workerJoin"
    command: "{{ workerJoinCmd.stdout }}"
  changed_when: False

## CleanUp
- name: Remove unneeded config files
  file:
    path: /tmp/kubeadm.yaml
    state: absent