- name: Copy file
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ../output/kubeconfig
    flat: yes

- name: Copy file
  copy:
    src: ../output/cloud-config
    dest: /tmp/cloud-config

- name: Apply cloud-config as secret 
  command: kubectl create secret -n kube-system generic cloud-config --from-file=cloud.conf=/tmp/cloud-config
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Install pip
  apt:
    pkg:
      - 
    state: present

- name: Install Helm
  become: false
  command: pip install pyhelm && pip install grpcio

- name: Install helm chart
  helm:
    host: localhost
    chart:
      name: stackit/ske-init
      source:
        type: repo
        location: https://registry.alpha.ske.eu01.stackit.cloud/chartrepo/stackit
    state: present
    name: ske-init
    namespace: kube-system