---
- hosts: masters[0]
  become: true
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
    - name: Kubeadm init 
      include_tasks: tasks/cluster-init.yaml